version: "3.4"

services:
  db:
    image: mariadb
    container_name: tarefas-db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - tarefas

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tarefas-app
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
    networks:
      - tarefas
    depends_on:
      - db

networks:
  tarefas:
    driver: bridge